image_folder = "path_to_your_image_folder/"

mask_folder = "path_to_your_mask_folder/"

test_image_folder = "path_to_your_test_image_folder/"

test_mask_folder = "path_to_your_test_mask_folder/"

num_epochs = 100

sam_model_name = "sam_base_vit"

sam_weight = 'path_to_your_weight/'

batch_size = 2

lr = 1e-5
